
 const appConstants={
     //login
    LOGIN_IN_PROGRESS:"LOGIN_IN_PROGRESS",
    LOGIN_SUCCES:"LOGIN_SUCCES",
    LOGIN_FAILURE:"LOGIN_ERROR",
    ADD_USERNAME:"ADD_USERNAME",
    //specializari
    GET_SPECIALIZARI_IN_PROGRESS:"GET_SPECIALIZARI_IN_PROGRESS",
    GET_SPECIALIZARI_SUCCESS:"GET_SPECIALIZARI_SUCCESS",
    GET_SPECIALIZARI_FAILURE:"GET_SPECIALIZARI_ERROR",
    SET_SPECIALIZARE:"SET_SPECIALIZARE",
    //medici
    GET_MEDICI_IN_PROGRESS:"GET_MEDICI_IN_PROGRESS",
    GET_MEDICI_SUCCESS:"GET_MEDICI_SUCCESS",
    GET_MEDICI_FAILURE:"GET_MEDICI_ERROR",
    //medic
    GET_PROFILMEDIC_IN_PROGRESS:"GET_PROFILMEDIC_IN_PROGRESS",
    GET_PROFILMEDIC_SUCCESS:"GET_PROFILMEDIC_SUCCESS",
    GET_PROFILMEDIC_FAILURE:"GET_PROFILMEDIC_ERROR"
}

export default appConstants;