
 const appConstants={
     //login
    LOGIN_IN_PROGRESS:"LOGIN_IN_PROGRESS",
    LOGIN_SUCCES:"LOGIN_SUCCES",
    LOGIN_FAILURE:"LOGIN_ERROR",
    ADD_USERNAME:"ADD_USERNAME",
    //specializari
    GET_SPECIALIZARI_IN_PROGRESS:"GET_SPECIALIZARI_IN_PROGRESS",
    GET_SPECIALIZARI_SUCCESS:"GET_SPECIALIZARI_SUCCESS",
    GET_SPECIALIZARI_FAILURE:"GET_SPECIALIZARI_ERROR",
    SET_SPECIALIZARE:"SET_SPECIALIZARE"
}

export default appConstants;