
 const appConstants={
     //login
    LOGIN_IN_PROGRESS:"LOGIN_IN_PROGRESS",
    LOGIN_SUCCES:"LOGIN_SUCCES",
    LOGIN_FAILURE:"LOGIN_ERROR",
    ADD_USERNAME:"ADD_USERNAME",
    //specializari
    GET_SPECIALIZARI_IN_PROGRESS:"GET_SPECIALIZARI_IN_PROGRESS",
    GET_SPECIALIZARI_SUCCESS:"GET_SPECIALIZARI_SUCCESS",
    GET_SPECIALIZARI_FAILURE:"GET_SPECIALIZARI_ERROR",
    SET_SPECIALIZARE:"SET_SPECIALIZARE",
    //medici
    GET_MEDICI_IN_PROGRESS:"GET_MEDICI_IN_PROGRESS",
    GET_MEDICI_SUCCESS:"GET_MEDICI_SUCCESS",
    GET_MEDICI_FAILURE:"GET_MEDICI_ERROR",
    //medic
    GET_PROFILMEDIC_IN_PROGRESS:"GET_PROFILMEDIC_IN_PROGRESS",
    GET_PROFILMEDIC_SUCCESS:"GET_PROFILMEDIC_SUCCESS",
    GET_PROFILMEDIC_FAILURE:"GET_PROFILMEDIC_ERROR",
    //recenziiMedic
    GET_RECENZIIMEDIC_IN_PROGRESS:"GET_RECENZIIMEDIC_IN_PROGRESS",
    GET_RECENZIIMEDIC_SUCCESS:"GET_RECENZIIMEDIC_SUCCESS",
    GET_RECENZIIMEDIC_FAILURE:"GET_RECENZIIMEDIC_ERROR",
    //servicii
    GET_SERVICII_IN_PROGRESS:"GET_SERVICII_IN_PROGRESS",
    GET_SERVICII_SUCCESS:"GET_SERVICII_SUCCESS",
    GET_SERVICII_FAILURE:"GET_SERVICII_ERROR",
    //program
    GET_PROGRAM_IN_PROGRESS:"GET_PROGRAM_IN_PROGRESS",
    GET_PROGRAM_SUCCESS:" GET_PROGRAM_SUCCESS",
    GET_PROGRAM_FAILURE:"GET_PROGRAM_ERROR",
    //cabinete
    GET_CABINETE_IN_PROGRESS:"GET_CABINETE_IN_PROGRESS",
    GET_CABINETE_SUCCESS:" GET_CABINETE_SUCCESS",
    GET_CABINETE_FAILURE:"GET_CABINETE_ERROR",
    //programari
    GET_PROGRAMARI_IN_PROGRESS:"GET_PROGRAMARI_IN_PROGRESS",
    GET_PROGRAMARI_SUCCESS:"GET_PROGRAMARI_SUCCESS",
    GET_PROGRAMARI_FAILURE:"GET_PROGRAMARI_ERROR",
    //cabinet
    GET_PROFILCABINET_IN_PROGRESS:" GET_PROFILCABINET_IN_PROGRESS",
    GET_PRIFILCABINET_SUCCESS:"GET_PRIFILCABINET_SUCCESS",
    GET_PROFILCABINET_FAILURE:"GET_PROFILCABINET_ERROR",   
}

export default appConstants;